RAW_PART1 = [
  {
    "id": "venice_0001",
    "title": "Bridge of Sighs",
    "caption": "1859 J.M.W. Turner",
    "creator": "Unknown Artist",
    "year": 1859,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433686, "lng": 12.341026 },
    "imageFile": "Venmap-1.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0002",
    "title": "Floating Bridge",
    "caption": "Photochrom Zürich, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.431022, "lng": 12.335439 },
    "imageFile": "Venmap-10.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0003",
    "title": "Campo Sant' Anzolo",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.434296, "lng": 12.332177 },
    "imageFile": "Venmap-100.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0004",
    "title": "North Facade of the Basilica",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434741, "lng": 12.3393 },
    "imageFile": "Venmap-101.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0005",
    "title": "Scene along the Grand Canal",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442608, "lng": 12.328069 },
    "imageFile": "Venmap-102.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0006",
    "title": "Closeup of Saint Mark's Horses",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434562, "lng": 12.339308 },
    "imageFile": "Venmap-103.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0007",
    "title": "Campo Santa Maria Formosa",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437343, "lng": 12.340944 },
    "imageFile": "Venmap-104.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0008",
    "title": "Grand Canal facing the Cannaregio Canal",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442306, "lng": 12.326365 },
    "imageFile": "Venmap-105.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0009",
    "title": "Grand Canal View",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431676, "lng": 12.328357 },
    "imageFile": "Venmap-106.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0010",
    "title": "Rio del Palazzo",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.435251, "lng": 12.340462 },
    "imageFile": "Venmap-107.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0011",
    "title": "Rio di Santa Marina",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43873, "lng": 12.339786 },
    "imageFile": "Venmap-108.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0012",
    "title": "Vittorio Emanuele II Monument",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.4338, "lng": 12.34334 },
    "imageFile": "Venmap-109.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0013",
    "title": "Palazzo Contarini and Rio de San Trovaso",
    "caption": "Andrew Fisher Bunner",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431777, "lng": 12.326892 },
    "imageFile": "Venmap-11.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0014",
    "title": "Colleoni Statue",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.4393, "lng": 12.341134 },
    "imageFile": "Venmap-110.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0015",
    "title": "Viw of the Basilica Santa Maria della Salute",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431625, "lng": 12.333709 },
    "imageFile": "Venmap-111.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0016",
    "title": "Corner of Doge's Palace",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433424, "lng": 12.340082 },
    "imageFile": "Venmap-112.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0017",
    "title": "Rio San Barnaba",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433185, "lng": 12.324334 },
    "imageFile": "Venmap-113.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0018",
    "title": "Ponte del Paradiso",
    "caption": "Photochrom Zürich, early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437575, "lng": 12.340063 },
    "imageFile": "Venmap-114.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0019",
    "title": "View from San Toma Vaporetto Stop",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.435327, "lng": 12.327941 },
    "imageFile": "Venmap-116.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0020",
    "title": "Campo San Vio",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430675, "lng": 12.330092 },
    "imageFile": "Venmap-117.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0021",
    "title": "Rio della Sensa",
    "caption": "Tomaso Filippi, Late 19th century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.444455, "lng": 12.333661 },
    "imageFile": "Venmap-118.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0022",
    "title": "San Giorio Maggiore",
    "caption": "Claude Monet, 1908",
    "creator": "Unknown Artist",
    "year": 1908,
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432479, "lng": 12.349537 },
    "imageFile": "Venmap-12.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0023",
    "title": "Rio Ospedaletto",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438433, "lng": 12.341649 },
    "imageFile": "Venmap-120.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0024",
    "title": "Rio San Martin",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433489, "lng": 12.348142 },
    "imageFile": "Venmap-121.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0025",
    "title": "Rio dei Tre Ponit",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.436876, "lng": 12.319234 },
    "imageFile": "Venmap-122.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0026",
    "title": "Staircase, Palazzo Contarini del Bovolo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434882, "lng": 12.334677 },
    "imageFile": "Venmap-123.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0027",
    "title": "Rio de le Toreseie",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.43039, "lng": 12.330745 },
    "imageFile": "Venmap-124.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0028",
    "title": "Rio delle Tete",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438844, "lng": 12.330933 },
    "imageFile": "Venmap-125.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0029",
    "title": "Rio Noali",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442631, "lng": 12.333382 },
    "imageFile": "Venmap-126.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0030",
    "title": "Rio Albrizzi",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438261, "lng": 12.330328 },
    "imageFile": "Venmap-127.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0031",
    "title": "View from the Piazzetta dei Leoncini",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434741, "lng": 12.3393 },
    "imageFile": "Venmap-128.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0032",
    "title": "Outer apse of the Frari",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.436748, "lng": 12.32556 },
    "imageFile": "Venmap-129.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0033",
    "title": "Saint mark's Square and the Basilica",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2009,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433894, "lng": 12.337712 },
    "imageFile": "Venmap-13.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0034",
    "title": "Rio di San Canciano",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.440237, "lng": 12.339446 },
    "imageFile": "Venmap-130.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0035",
    "title": "View along Riva degli Schiavoni",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433853, "lng": 12.344113 },
    "imageFile": "Venmap-131.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0036",
    "title": "Rio San Polo",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437864, "lng": 12.328248 },
    "imageFile": "Venmap-132.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0037",
    "title": "Rio dei Carmini",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431424, "lng": 12.321926 },
    "imageFile": "Venmap-133.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0038",
    "title": "Rio di San provolo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.435567, "lng": 12.343296 },
    "imageFile": "Venmap-134.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0039",
    "title": "Courtyard, San Giovanni Evangelista",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438281, "lng": 12.326228 },
    "imageFile": "Venmap-135.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0040",
    "title": "Punta della Dogana and La Salute",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.431365, "lng": 12.338051 },
    "imageFile": "Venmap-136.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0041",
    "title": "Rio San Barnaba",
    "caption": "Luigia Alzetta, late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433171, "lng": 12.324884 },
    "imageFile": "Venmap-137.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0042",
    "title": "Doorway, Scuola Grande di San Marco",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439475, "lng": 12.341303 },
    "imageFile": "Venmap-138.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0043",
    "title": "Piazza San Marco and the Basilica",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434059, "lng": 12.338475 },
    "imageFile": "Venmap-139.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0044",
    "title": "Piazza San Marco",
    "caption": "Francesco Guardi, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433801, "lng": 12.337417 },
    "imageFile": "Venmap-14.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0045",
    "title": "Ponte Bernardo",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438625, "lng": 12.329441 },
    "imageFile": "Venmap-140.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0046",
    "title": "The Clock Tower",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43437, "lng": 12.338875 },
    "imageFile": "Venmap-141.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0047",
    "title": "Campo Santa Ternita",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.437214, "lng": 12.348715 },
    "imageFile": "Venmap-142.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0048",
    "title": "The Giant Stairs",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434332, "lng": 12.340304 },
    "imageFile": "Venmap-143.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0049",
    "title": "Crowd in Piazza San Marco",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434144, "lng": 12.338708 },
    "imageFile": "Venmap-144.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0050",
    "title": "Rio Priuli",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.441537, "lng": 12.336133 },
    "imageFile": "Venmap-145.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0051",
    "title": "Rio Meravegie",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.43166, "lng": 12.326873 },
    "imageFile": "Venmap-146.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0052",
    "title": "Porta della Carta",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434171, "lng": 12.339548 },
    "imageFile": "Venmap-147.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0053",
    "title": "View from Fondaco dei Turchi",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442114, "lng": 12.32863 },
    "imageFile": "Venmap-148.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0054",
    "title": "San Moise Facade",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433064, "lng": 12.335583 },
    "imageFile": "Venmap-149.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0055",
    "title": "Rio San Barnaba",
    "caption": "Maurice Bompard",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433253, "lng": 12.3247 },
    "imageFile": "Venmap-15.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0056",
    "title": "Rio della Torreselle",
    "caption": "Luigia Alzetta, late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430384, "lng": 12.332175 },
    "imageFile": "Venmap-150.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0057",
    "title": "Fondamenta dei Ormesini",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445949, "lng": 12.326825 },
    "imageFile": "Venmap-151.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0058",
    "title": "Rio di Giovanni Latero",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43835, "lng": 12.342108 },
    "imageFile": "Venmap-152.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0059",
    "title": "Rio dei Mendicanti",
    "caption": "Possemiers, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439133, "lng": 12.341031 },
    "imageFile": "Venmap-153.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0060",
    "title": "Rio Tera ai Saloni",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.43009, "lng": 12.333534 },
    "imageFile": "Venmap-154.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0061",
    "title": "Women on the Rialto Bridge",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437989, "lng": 12.336259 },
    "imageFile": "Venmap-155.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0062",
    "title": "San Giacomo di Rialto market",
    "caption": "Luigia Alzetta, late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438649, "lng": 12.335076 },
    "imageFile": "Venmap-156.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0063",
    "title": "Piazzetta San Marco",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433553, "lng": 12.339786 },
    "imageFile": "Venmap-157.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0064",
    "title": "Piazzetta San Marco",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43396, "lng": 12.339385 },
    "imageFile": "Venmap-158.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0065",
    "title": "Rio San barnaba",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433414, "lng": 12.326665 },
    "imageFile": "Venmap-159.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0066",
    "title": "Piazza San Marco Scene",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2012,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43437, "lng": 12.338875 },
    "imageFile": "Venmap-16.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0067",
    "title": "Rio San Trovaso",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.432385, "lng": 12.327446 },
    "imageFile": "Venmap-160.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0068",
    "title": "Grand Canal Scene",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436752, "lng": 12.334393 },
    "imageFile": "Venmap-161.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0069",
    "title": "Ponte dei Meloni",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437534, "lng": 12.331582 },
    "imageFile": "Venmap-162.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0070",
    "title": "Well in Campo San Vio",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430697, "lng": 12.330161 },
    "imageFile": "Venmap-163.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0071",
    "title": "Calle de la Scuola, Carmini",
    "caption": "Tomaso Filippi, Late 19th century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.43357, "lng": 12.322436 },
    "imageFile": "Venmap-164.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0072",
    "title": "Palazzo Giustinian",
    "caption": "Carlo Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.430996, "lng": 12.336727 },
    "imageFile": "Venmap-165.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0073",
    "title": "Boats on the Riva degli Schiavoni",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433131, "lng": 12.348306 },
    "imageFile": "Venmap-166.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0074",
    "title": "Well in Campo San giacomo del Orio",
    "caption": "G. Brasolin, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.440354, "lng": 12.327588 },
    "imageFile": "Venmap-167.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0075",
    "title": "Iron Accademia Bridge",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431586, "lng": 12.328615 },
    "imageFile": "Venmap-168.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0076",
    "title": "Rio della Sensa",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.446689, "lng": 12.327135 },
    "imageFile": "Venmap-169.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0077",
    "title": "View from the Porta della Carta",
    "caption": "William Wyld, 1840",
    "creator": "Unknown Artist",
    "year": 2013,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434232, "lng": 12.33977 },
    "imageFile": "Venmap-17.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0078",
    "title": "Ponte del Paradiso",
    "caption": "Fratelli Alinari, Late 19th century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437588, "lng": 12.340051 },
    "imageFile": "Venmap-170.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0079",
    "title": "Palazzo Balbi",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.434737, "lng": 12.327364 },
    "imageFile": "Venmap-171.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0080",
    "title": "Rio del Palazzo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.435403, "lng": 12.340423 },
    "imageFile": "Venmap-172.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0081",
    "title": "View from San Giorgio Maggiore",
    "caption": "Unknown, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.429763, "lng": 12.34266 },
    "imageFile": "Venmap-173.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0082",
    "title": "Rio dell' Angelo",
    "caption": "Tomaso Filippi, Late 19th century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.435815, "lng": 12.339892 },
    "imageFile": "Venmap-174.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0083",
    "title": "Rio della Misericordia",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.444883, "lng": 12.330619 },
    "imageFile": "Venmap-175.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0084",
    "title": "Rio Bernardo",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438637, "lng": 12.329414 },
    "imageFile": "Venmap-176.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0085",
    "title": "Zattere Waterfront",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429798, "lng": 12.325183 },
    "imageFile": "Venmap-177.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0086",
    "title": "Well in Campo San Aponal",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437771, "lng": 12.332317 },
    "imageFile": "Venmap-178.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0087",
    "title": "Campo San Boldo",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.439573, "lng": 12.328504 },
    "imageFile": "Venmap-179.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0088",
    "title": "Campo Santa Margherita",
    "caption": "Ettore Tito, 1884",
    "creator": "Unknown Artist",
    "year": 2013,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.434357, "lng": 12.323606 },
    "imageFile": "Venmap-18.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0089",
    "title": "High water in front of the Doge's Palace",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433557, "lng": 12.341246 },
    "imageFile": "Venmap-180.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0090",
    "title": "Rialto Bridge",
    "caption": "Unknown, About 1920",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437149, "lng": 12.335015 },
    "imageFile": "Venmap-181.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0091",
    "title": "Campo San Ternita",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.437312, "lng": 12.348785 },
    "imageFile": "Venmap-182.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0092",
    "title": "Campo San Polo",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437599, "lng": 12.330013 },
    "imageFile": "Venmap-183.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0093",
    "title": "Rialto Fish Market",
    "caption": "G. Brasolin, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439538, "lng": 12.334623 },
    "imageFile": "Venmap-184.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0094",
    "title": "Grand Canal scene and the Rialto Bridge",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436611, "lng": 12.333722 },
    "imageFile": "Venmap-185.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0095",
    "title": "Well in Campo Santi Giovanni e Paolo",
    "caption": "A. Stieglitz",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439114, "lng": 12.341608 },
    "imageFile": "Venmap-186.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0096",
    "title": "Rialto Market",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438895, "lng": 12.334678 },
    "imageFile": "Venmap-187.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0097",
    "title": "Campo del Ghetto Nuovo",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445408, "lng": 12.326883 },
    "imageFile": "Venmap-188.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0098",
    "title": "View Along the Zattere",
    "caption": "Francesco Guardi, 1780",
    "creator": "Unknown Artist",
    "year": 2013,
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.428582, "lng": 12.328306 },
    "imageFile": "Venmap-19.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0099",
    "title": "Monument to Victor Emmanuel II",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433907, "lng": 12.343495 },
    "imageFile": "Venmap-190.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0100",
    "title": "Washing, Rio di San Stin",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437613, "lng": 12.327065 },
    "imageFile": "Venmap-191.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0101",
    "title": "Santa Maria del Giglio",
    "caption": "Unknown, Early 20th Century Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.432475, "lng": 12.333042 },
    "imageFile": "Venmap-192.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0102",
    "title": "South Facade of The Basilica",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434171, "lng": 12.339548 },
    "imageFile": "Venmap-193.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0103",
    "title": "Garibaldi Statue",
    "caption": "Tomaso Filippi, 1880s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432179, "lng": 12.354846 },
    "imageFile": "Venmap-194.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0104",
    "title": "Rio San Barnaba",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433265, "lng": 12.324503 },
    "imageFile": "Venmap-195.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0105",
    "title": "View of the Rialto Bridge",
    "caption": "G. Somer, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437187, "lng": 12.334994 },
    "imageFile": "Venmap-196.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0106",
    "title": "Palazzo Vendramin Grimani",
    "caption": "C. Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.436064, "lng": 12.330847 },
    "imageFile": "Venmap-197.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0107",
    "title": "Grand Canal View",
    "caption": "Carlo Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.430715, "lng": 12.334712 },
    "imageFile": "Venmap-198.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0108",
    "title": "Piazzetta San Marco",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433553, "lng": 12.339786 },
    "imageFile": "Venmap-199.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0109",
    "title": "Ca' d'Oro",
    "caption": "Around 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.440446, "lng": 12.333416 },
    "imageFile": "Venmap-2.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0110",
    "title": "PThe Piazzetta and Columns",
    "caption": "Giorgio Sommer, 1865",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433974, "lng": 12.339387 },
    "imageFile": "Venmap-20.webp",
    "rights": "Public Domain",
    "inBounds": True
  }
]
