RAW_PART2 = [
  {
    "id": "venice_0111",
    "title": "View of the Doge's Palace and Columns",
    "caption": "Domenico Bresolin, 1850s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433042, "lng": 12.339406 },
    "imageFile": "Venmap-200.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0112",
    "title": "Piazza San Marco",
    "caption": "Unknown, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433894, "lng": 12.337712 },
    "imageFile": "Venmap-201.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0113",
    "title": "Grand Canal and Rialto Bridge",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436476, "lng": 12.33364 },
    "imageFile": "Venmap-202.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0114",
    "title": "Rio della Erbe with swimming children",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439821, "lng": 12.339986 },
    "imageFile": "Venmap-203.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0115",
    "title": "Corner of the Doge's Palace",
    "caption": "Domenico Bresolin, 1850s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433445, "lng": 12.340086 },
    "imageFile": "Venmap-204.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0116",
    "title": "Bridges over Rio del Palazzo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434957, "lng": 12.340564 },
    "imageFile": "Venmap-205.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0117",
    "title": "Riva degli Schiavoni",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433765, "lng": 12.342542 },
    "imageFile": "Venmap-206.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0118",
    "title": "Hotel Danieli",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433674, "lng": 12.342103 },
    "imageFile": "Venmap-207.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0119",
    "title": "Fondaco dei Turchi",
    "caption": "Carlo Ponti, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442307, "lng": 12.329028 },
    "imageFile": "Venmap-208.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0120",
    "title": "View of San Giorgio Maggiore",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43401, "lng": 12.339077 },
    "imageFile": "Venmap-209.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0121",
    "title": "View from the Campanile",
    "caption": "C. Naya, 1868",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434136, "lng": 12.339062 },
    "imageFile": "Venmap-21.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0122",
    "title": "Sculpture and columns, corner of Doge's Palace",
    "caption": "Carlo Naya, mid 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434164, "lng": 12.339641 },
    "imageFile": "Venmap-210.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0123",
    "title": "Scuola Grande di San Marco",
    "caption": "Carlo Ponti, Mid 19th Century, mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43934, "lng": 12.341172 },
    "imageFile": "Venmap-211.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0124",
    "title": "Riva degli Schiavoni",
    "caption": "Carlo Naya, mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433806, "lng": 12.3435 },
    "imageFile": "Venmap-212.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0125",
    "title": "Portal to Campo San Zaccaria",
    "caption": "Carlo Ponti, Mid 19th Century, mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434961, "lng": 12.342554 },
    "imageFile": "Venmap-213.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0126",
    "title": "Tintoretto's House and canal",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445295, "lng": 12.332077 },
    "imageFile": "Venmap-214.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0127",
    "title": "Campo Santo Stefano",
    "caption": "G. Brasolin, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433385, "lng": 12.330413 },
    "imageFile": "Venmap-215.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0128",
    "title": "Rio San Giuseppi",
    "caption": "G. Brasolin, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429696, "lng": 12.325595 },
    "imageFile": "Venmap-216.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0129",
    "title": "Iron Scalzi Bridge over Grand Canal",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.440958, "lng": 12.321837 },
    "imageFile": "Venmap-217.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0130",
    "title": "San Pietro di Castello",
    "caption": "Photochrom Zürich, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433764, "lng": 12.358021 },
    "imageFile": "Venmap-218.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0131",
    "title": "Swimming in the Canareggio Canal",
    "caption": "Tomaso Filippi, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.443754, "lng": 12.324429 },
    "imageFile": "Venmap-219.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0132",
    "title": "Rialto Vegetable Market",
    "caption": "P. Salviati, late 19th Century",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438935, "lng": 12.335549 },
    "imageFile": "Venmap-22.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0133",
    "title": "Stringing Beads on the Island of San Pietro",
    "caption": "Tommaso Filippi, 1895",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433716, "lng": 12.358525 },
    "imageFile": "Venmap-220.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0134",
    "title": "Girl in Campo Santa Margherita",
    "caption": "Tomaso Filippi, Late 19th century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433923, "lng": 12.323215 },
    "imageFile": "Venmap-221.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0135",
    "title": "Rio de San Aponal",
    "caption": "Tomaso Filippi, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438151, "lng": 12.331612 },
    "imageFile": "Venmap-222.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0136",
    "title": "Boat at the Rialto Market",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438861, "lng": 12.335773 },
    "imageFile": "Venmap-223.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0137",
    "title": "Salizada Santa Giustina",
    "caption": "Tomaso Filippi, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437382, "lng": 12.346919 },
    "imageFile": "Venmap-224.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0138",
    "title": "Floating Bridge to San Michele for All Saints Day",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.442893, "lng": 12.340884 },
    "imageFile": "Venmap-225.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0139",
    "title": "Campo della Maddalena",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.443208, "lng": 12.331142 },
    "imageFile": "Venmap-226.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0140",
    "title": "Corte Seconda del Milion",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438803, "lng": 12.337876 },
    "imageFile": "Venmap-227.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0141",
    "title": "Rio dell'Abbazia",
    "caption": "G. Brocca, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.44334, "lng": 12.33578 },
    "imageFile": "Venmap-228.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0142",
    "title": "Rio dei Carmini",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433308, "lng": 12.320129 },
    "imageFile": "Venmap-229.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0143",
    "title": "Columns of the Doge's Palace",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433624, "lng": 12.340057 },
    "imageFile": "Venmap-23.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0144",
    "title": "Ponte dell'Accademia",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431587, "lng": 12.328127 },
    "imageFile": "Venmap-230.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0145",
    "title": "Rio de Santa Ana",
    "caption": "G. Sciutto, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432626, "lng": 12.357647 },
    "imageFile": "Venmap-231.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0146",
    "title": "Ca Pesaro",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.44124, "lng": 12.332396 },
    "imageFile": "Venmap-232.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0147",
    "title": "Fondamenta S. Anna",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432623, "lng": 12.357939 },
    "imageFile": "Venmap-233.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0148",
    "title": "Rio della Sensa",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.444452, "lng": 12.333653 },
    "imageFile": "Venmap-234.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0149",
    "title": "Rio della Pieta",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434713, "lng": 12.345669 },
    "imageFile": "Venmap-235.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0150",
    "title": "Rio del Ognissanti",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430953, "lng": 12.323852 },
    "imageFile": "Venmap-236.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0151",
    "title": "Rio di S. Girolamo",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.446853, "lng": 12.32324 },
    "imageFile": "Venmap-237.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0152",
    "title": "View along Campiello Santa Maria Zobenigo",
    "caption": "F. Ongania, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431002, "lng": 12.333105 },
    "imageFile": "Venmap-238.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0153",
    "title": "Grand Canal near Fondamenta del Monastero",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438846, "lng": 12.31994 },
    "imageFile": "Venmap-239.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0154",
    "title": "Palazzo Bernardo",
    "caption": "P. Salviati, late 19th Century",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.435997, "lng": 12.330813 },
    "imageFile": "Venmap-24.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0155",
    "title": "Campo Sant'Angelo",
    "caption": "Canaletto, 1730s",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.434481, "lng": 12.332258 },
    "imageFile": "Venmap-240.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0156",
    "title": "San Trovaso Gondola Workshop",
    "caption": "C. Naya 1890",
    "creator": "Unknown Artist",
    "year": 1890,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430046, "lng": 12.326082 },
    "imageFile": "Venmap-241.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0157",
    "title": "People at a well in Campo Santa Maria Formosa",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437611, "lng": 12.340773 },
    "imageFile": "Venmap-242.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0158",
    "title": "Rio di San Giuseppe",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.430382, "lng": 12.355775 },
    "imageFile": "Venmap-243.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0159",
    "title": "Campo San Giacomo di Rialto",
    "caption": "Giuseppe Canella",
    "creator": "Unknown Artist",
    "year": 2020,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438724, "lng": 12.335157 },
    "imageFile": "Venmap-245.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0160",
    "title": "View of Campo dei Frari",
    "caption": "Michele Mareschi, 18th Century",
    "creator": "Unknown Artist",
    "year": 2020,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437253, "lng": 12.32728 },
    "imageFile": "Venmap-246.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0161",
    "title": "View From Ca' Rezzonico",
    "caption": "Beryl De Selincourt",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433368, "lng": 12.327031 },
    "imageFile": "Venmap-247.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0162",
    "title": "View of San Samuele",
    "caption": "Frederico Del Campo, 1920",
    "creator": "Unknown Artist",
    "year": 1920,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433361, "lng": 12.327042 },
    "imageFile": "Venmap-248.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0163",
    "title": "The Clock Tower",
    "caption": "",
    "creator": "Unknown Artist",
    "year": 2022,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434141, "lng": 12.33927 },
    "imageFile": "Venmap-249.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0164",
    "title": "View from San Giorgio Bell Tower",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.429525, "lng": 12.343836 },
    "imageFile": "Venmap-25.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0165",
    "title": "Corte San Marco",
    "caption": "Noè Bordignon, 1884",
    "creator": "Unknown Artist",
    "year": 2023,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.435165, "lng": 12.320216 },
    "imageFile": "Venmap-250.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0166",
    "title": "Bridge to Calle paradiso",
    "caption": "Albert Emil Kirchner, 19th Century",
    "creator": "Unknown Artist",
    "year": 2023,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43749, "lng": 12.340192 },
    "imageFile": "Venmap-251.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0167",
    "title": "Court of the Doge's Palace",
    "caption": "Affleck, Andrew F. 1915",
    "creator": "Unknown Artist",
    "year": 1915,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434045, "lng": 12.340288 },
    "imageFile": "Venmap-252.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0168",
    "title": "Grand Canal and Campo della Carità",
    "caption": "Canaletto, 1730s",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.432473, "lng": 12.327669 },
    "imageFile": "Venmap-253.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0169",
    "title": "Rialto Bridge",
    "caption": "Francesco Guardi, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43731, "lng": 12.334873 },
    "imageFile": "Venmap-254.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0170",
    "title": "Piazza San Marco",
    "caption": "Luca Carlevaris, 1709",
    "creator": "Unknown Artist",
    "year": 1709,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433831, "lng": 12.337564 },
    "imageFile": "Venmap-255.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0171",
    "title": "View of Salute and the Dogana",
    "caption": "Francesco Guardi, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.432473, "lng": 12.337619 },
    "imageFile": "Venmap-256.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0172",
    "title": "San Marco Waterfront",
    "caption": "Luca Carlevaris, 1709",
    "creator": "Unknown Artist",
    "year": 1709,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433559, "lng": 12.341303 },
    "imageFile": "Venmap-257.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0173",
    "title": "Squero San Andrea",
    "caption": "Andrew Fisher Bunner, 1885",
    "creator": "Unknown Artist",
    "year": 1885,
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.444661, "lng": 12.333494 },
    "imageFile": "Venmap-258.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0174",
    "title": "San Barnabas e Carmine",
    "caption": "Andrew Fisher Bunner, 1885",
    "creator": "Unknown Artist",
    "year": 1885,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433441, "lng": 12.327026 },
    "imageFile": "Venmap-259.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0175",
    "title": "Gates of the Arsenale",
    "caption": "Bonaldi &amp; Tarraghetta, 1855",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434513, "lng": 12.350284 },
    "imageFile": "Venmap-26.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0176",
    "title": "San Pietro di Castello",
    "caption": "Andrew Fisher Bunner, 1885",
    "creator": "Unknown Artist",
    "year": 1885,
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433669, "lng": 12.357933 },
    "imageFile": "Venmap-260.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0177",
    "title": "View From Fondamenta Morosina",
    "caption": "Andrew Fisher Bunner, 1883",
    "creator": "Unknown Artist",
    "year": 1883,
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433999, "lng": 12.348633 },
    "imageFile": "Venmap-261.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0178",
    "title": "Canal and Church of Santa Maria dei Miracoli",
    "caption": "Andrew Fisher Bunner, 1883",
    "creator": "Unknown Artist",
    "year": 1883,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439826, "lng": 12.33942 },
    "imageFile": "Venmap-262.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0179",
    "title": "Sunset View of Santa Maria della Salute",
    "caption": "William Stanley Haseltine, 1870",
    "creator": "Unknown Artist",
    "year": 1870,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.430957, "lng": 12.341226 },
    "imageFile": "Venmap-263.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0180",
    "title": "Piazza San Marco",
    "caption": "Antonio Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434388, "lng": 12.338614 },
    "imageFile": "Venmap-264.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0181",
    "title": "Court of the Doge's Palace",
    "caption": "Antonio Joli, 1742",
    "creator": "Unknown Artist",
    "year": 1742,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433883, "lng": 12.340368 },
    "imageFile": "Venmap-265.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0182",
    "title": "Ca' d'Oro",
    "caption": "Antonietta Brandeis 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.440032, "lng": 12.333643 },
    "imageFile": "Venmap-266.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0183",
    "title": "Zattere Waterfront",
    "caption": "Otto Henry Bacher, 1880",
    "creator": "Unknown Artist",
    "year": 1880,
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429652, "lng": 12.325621 },
    "imageFile": "Venmap-267.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0184",
    "title": "Camp dei Frari",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437167, "lng": 12.327359 },
    "imageFile": "Venmap-268.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0185",
    "title": "Canmpo Apostoli",
    "caption": "Francis Sydney Unwin, 1911",
    "creator": "Unknown Artist",
    "year": 1911,
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.440019, "lng": 12.336599 },
    "imageFile": "Venmap-269.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0186",
    "title": "View fron the Rialto Bridge",
    "caption": "Bonaldi &amp; Tarraghetta, 1855",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437354, "lng": 12.33485 },
    "imageFile": "Venmap-27.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0187",
    "title": "Fondamenta Nouve",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.443298, "lng": 12.340187 },
    "imageFile": "Venmap-270.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0188",
    "title": "Rialto Bridge",
    "caption": "William James Müller, 1835",
    "creator": "Unknown Artist",
    "year": 1835,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439407, "lng": 12.336186 },
    "imageFile": "Venmap-271.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0189",
    "title": "Scuola di San Marco",
    "caption": "Jules-Romain Joyant, 1830",
    "creator": "Unknown Artist",
    "year": 1830,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438895, "lng": 12.340766 },
    "imageFile": "Venmap-272.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0190",
    "title": "Campo si San Giovanni e Paolo",
    "caption": "Bernardo Bellotto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439132, "lng": 12.341065 },
    "imageFile": "Venmap-273.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0191",
    "title": "Grand Canal Palazzos",
    "caption": "William Callow, 1866",
    "creator": "Unknown Artist",
    "year": 1866,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.431807, "lng": 12.334933 },
    "imageFile": "Venmap-274.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0192",
    "title": "San Pietro di Castello",
    "caption": "Apollonio Facchinetti",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.435141, "lng": 12.358533 },
    "imageFile": "Venmap-275.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0193",
    "title": "Eveneing on the Grand Canal",
    "caption": "Friederich Nerly, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.43165, "lng": 12.32894 },
    "imageFile": "Venmap-276.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0194",
    "title": "The Rialto Market",
    "caption": "Louis Abel Truchet, early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439371, "lng": 12.336193 },
    "imageFile": "Venmap-277.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0195",
    "title": "Riva del Vin",
    "caption": "Maurice Prendergast, 1899",
    "creator": "Unknown Artist",
    "year": 1899,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43806, "lng": 12.335734 },
    "imageFile": "Venmap-278.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0196",
    "title": "Riva del Ferro",
    "caption": "Maurice Prendergast, 1898",
    "creator": "Unknown Artist",
    "year": 1898,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437923, "lng": 12.335974 },
    "imageFile": "Venmap-279.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0197",
    "title": "St. Mark's Square looking West",
    "caption": "Bonaldi &amp; Tarraghetta, 1855",
    "creator": "Unknown Artist",
    "year": 2014,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43437, "lng": 12.338875 },
    "imageFile": "Venmap-28.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0198",
    "title": "Corner of the Doge's Palace",
    "caption": "Rudolf von Alt, 1874",
    "creator": "Unknown Artist",
    "year": 1874,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434205, "lng": 12.339592 },
    "imageFile": "Venmap-280.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0199",
    "title": "Courtyard of the Palace",
    "caption": "Rudolf von Alt, 1864",
    "creator": "Unknown Artist",
    "year": 1864,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43393, "lng": 12.34016 },
    "imageFile": "Venmap-281.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0200",
    "title": "Campo San Canciano",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.4403, "lng": 12.338251 },
    "imageFile": "Venmap-282.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0201",
    "title": "Santa Maria dei Miracoli",
    "caption": "Ippolito Caffi, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439826, "lng": 12.339414 },
    "imageFile": "Venmap-283.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0202",
    "title": "Porta della Carta",
    "caption": "Antonietta Brandeis, 1886",
    "creator": "Unknown Artist",
    "year": 1886,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434077, "lng": 12.33932 },
    "imageFile": "Venmap-284.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0203",
    "title": "Rio de San Lorenzo",
    "caption": "Martín Rico y Ortega, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437021, "lng": 12.344288 },
    "imageFile": "Venmap-285.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0204",
    "title": "Fondaco dei Turchi",
    "caption": "Luigi Querena, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442082, "lng": 12.329086 },
    "imageFile": "Venmap-286.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0205",
    "title": "Well in the Courtyard of the Palace",
    "caption": "Friedrich Christian Nerly, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43406, "lng": 12.34016 },
    "imageFile": "Venmap-287.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0206",
    "title": "Campo San Giacomo di Rialto",
    "caption": "Thomas Ellison",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438669, "lng": 12.335107 },
    "imageFile": "Venmap-288.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0207",
    "title": "Visit of the Doge to San Zaccaria on Easter Day",
    "caption": "Gabriele Bella, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434784, "lng": 12.342951 },
    "imageFile": "Venmap-289.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0208",
    "title": "View near the Doge's Palace",
    "caption": "Al Thevenin",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433244, "lng": 12.34161 },
    "imageFile": "Venmap-29.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0209",
    "title": "Arenale Gate",
    "caption": "Canaletto, 1732",
    "creator": "Unknown Artist",
    "year": 1732,
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434295, "lng": 12.349997 },
    "imageFile": "Venmap-290.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0210",
    "title": "Calle Tintoretto",
    "caption": "Federico del Campo, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437043, "lng": 12.324776 },
    "imageFile": "Venmap-291.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0211",
    "title": "Campo San Boldo",
    "caption": "John Singer Sargent, 1904",
    "creator": "Unknown Artist",
    "year": 1904,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.439518, "lng": 12.328417 },
    "imageFile": "Venmap-292.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0212",
    "title": "Campo San Giovanni e Paolo",
    "caption": "Federico Moja, 1842",
    "creator": "Unknown Artist",
    "year": 1842,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439121, "lng": 12.341452 },
    "imageFile": "Venmap-293.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0213",
    "title": "Santa Maria dell'Orto",
    "caption": "Moro and Rebellato, 1858",
    "creator": "Unknown Artist",
    "year": 1858,
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.44594, "lng": 12.332462 },
    "imageFile": "Venmap-294.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0214",
    "title": "Grand Canal and La Salute",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.431945, "lng": 12.335513 },
    "imageFile": "Venmap-295.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0215",
    "title": "Waterfront and Doge's Palace",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433302, "lng": 12.33997 },
    "imageFile": "Venmap-296.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0216",
    "title": "Piazza San Marco and the Basilica",
    "caption": "M. Prendergast, 1898",
    "creator": "Unknown Artist",
    "year": 1898,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434284, "lng": 12.338658 },
    "imageFile": "Venmap-297.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0217",
    "title": "Palazzo Grimani",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.436234, "lng": 12.33275 },
    "imageFile": "Venmap-298.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0218",
    "title": "San Giorgio Maggiore by Moonlight",
    "caption": "Henry Pether, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.431354, "lng": 12.342208 },
    "imageFile": "Venmap-299.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0219",
    "title": "Church of the Scalzi",
    "caption": "Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.44088, "lng": 12.32275 },
    "imageFile": "Venmap-3.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0220",
    "title": "Corner of La Salute",
    "caption": "Luigi Maria Galea",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.430254, "lng": 12.334483 },
    "imageFile": "Venmap-30.webp",
    "rights": "Public Domain",
    "inBounds": True
  }
]
