RAW_PART3 = [
  {
    "id": "venice_0221",
    "title": "Bridge Over Rio della Salute",
    "caption": "Arthur Streeton, 1908",
    "creator": "Unknown Artist",
    "year": 1908,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43044, "lng": 12.33446 },
    "imageFile": "Venmap-300.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0222",
    "title": "Gesuati Church and the Zattere",
    "caption": "Giovanni Pividor, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429378, "lng": 12.326615 },
    "imageFile": "Venmap-301.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0223",
    "title": "Rialto Bridge and The Grand Canal",
    "caption": "Samuel Prout, 1850",
    "creator": "Unknown Artist",
    "year": 1850,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436479, "lng": 12.333661 },
    "imageFile": "Venmap-302.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0224",
    "title": "View of Salute from Accademia",
    "caption": "Samuel Prout, 1850",
    "creator": "Unknown Artist",
    "year": 1850,
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431514, "lng": 12.328828 },
    "imageFile": "Venmap-303.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0225",
    "title": "The Arsenale Gates",
    "caption": "V.L. Vigano, 1850",
    "creator": "Unknown Artist",
    "year": 1850,
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434816, "lng": 12.349542 },
    "imageFile": "Venmap-304.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0226",
    "title": "The Frari",
    "caption": "V.L. Vigano, 1850",
    "creator": "Unknown Artist",
    "year": 1850,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437162, "lng": 12.327384 },
    "imageFile": "Venmap-305.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0227",
    "title": "Piazzetta San Marco",
    "caption": "Luca Carlevarijs, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433399, "lng": 12.339988 },
    "imageFile": "Venmap-306.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0228",
    "title": "Grand Canal and San Simeone Piccolo",
    "caption": "Francesco Guardi, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.441148, "lng": 12.322758 },
    "imageFile": "Venmap-307.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0229",
    "title": "Bridge of Sighs",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433719, "lng": 12.340945 },
    "imageFile": "Venmap-308.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0230",
    "title": "Doge's Palace and Bridge of Sighs",
    "caption": "Edward William Cooke, 1858",
    "creator": "Unknown Artist",
    "year": 1858,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433499, "lng": 12.341079 },
    "imageFile": "Venmap-309.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0231",
    "title": "Rialto Fish Market",
    "caption": "Ettore tito, 1893",
    "creator": "Unknown Artist",
    "year": 1893,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439832, "lng": 12.33441 },
    "imageFile": "Venmap-310.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0232",
    "title": "Rialto Fish Market",
    "caption": "Myles Birket Foster, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437682, "lng": 12.335895 },
    "imageFile": "Venmap-311.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0233",
    "title": "Riva dei Sette Martiri",
    "caption": "Maurice Prendergast, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.431059, "lng": 12.352976 },
    "imageFile": "Venmap-312.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0234",
    "title": "Piazza San Marco and the Basilica",
    "caption": "Ettore Tito, 1892",
    "creator": "Unknown Artist",
    "year": 1892,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434059, "lng": 12.338268 },
    "imageFile": "Venmap-313.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0235",
    "title": "Campo San Giacomo di Rialto",
    "caption": "Canaletto, 1760s",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438722, "lng": 12.335095 },
    "imageFile": "Venmap-314.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0236",
    "title": "View From Riva San Biasio",
    "caption": "Joseph Chapuy, 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432623, "lng": 12.34974 },
    "imageFile": "Venmap-315.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0237",
    "title": "San Stae",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.441497, "lng": 12.331013 },
    "imageFile": "Venmap-316.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0238",
    "title": "Rio del Palazzo and Bridge of Sighs",
    "caption": "Antonietta Brandeis",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434949, "lng": 12.340594 },
    "imageFile": "Venmap-317.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0239",
    "title": "Rio San Trovaso at the Grand Canal",
    "caption": "Antonietta Brandeis",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.432292, "lng": 12.327245 },
    "imageFile": "Venmap-318.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0240",
    "title": "Rio Madonna del Orto",
    "caption": "Antonietta Brandeis",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.444967, "lng": 12.334835 },
    "imageFile": "Venmap-319.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0241",
    "title": "Boats at the Rialto Market",
    "caption": "Antonietta Brandeis",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438685, "lng": 12.336252 },
    "imageFile": "Venmap-320.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0242",
    "title": "Church of the Redeemer",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.426451, "lng": 12.33263 },
    "imageFile": "Venmap-321.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0243",
    "title": "Cannaregio Canal and Ponte dei Tre Archi",
    "caption": "Francesco Guardi, 18th century, oil on canvas",
    "creator": "Unknown Artist",
    "year": 1780,
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445089, "lng": 12.321448 },
    "imageFile": "Venmap-322.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0244",
    "title": "Fondamenta dei Mendicanti",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.441502, "lng": 12.342319 },
    "imageFile": "Venmap-323.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0245",
    "title": "Piazza San Marco",
    "caption": "William Logsdail, 1883",
    "creator": "Unknown Artist",
    "year": 1883,
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434243, "lng": 12.338004 },
    "imageFile": "Venmap-324.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0246",
    "title": "Fondamenta de Quintavalle",
    "caption": "William Logsdail, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.433764, "lng": 12.35852 },
    "imageFile": "Venmap-325.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0247",
    "title": "Pigeons Outside Cafe Florian",
    "caption": "William Logsdail, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433829, "lng": 12.338377 },
    "imageFile": "Venmap-326.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0248",
    "title": "Grand Canal View",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.442306, "lng": 12.330166 },
    "imageFile": "Venmap-327.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0249",
    "title": "View From Ca' Rezzonico",
    "caption": "James Charles, 1892",
    "creator": "Unknown Artist",
    "year": 1892,
    "mediaType": "painting",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.433345, "lng": 12.327013 },
    "imageFile": "Venmap-328.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0250",
    "title": "Campiello Barbaro",
    "caption": "Konstantin Gorbatov, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.430441, "lng": 12.332226 },
    "imageFile": "Venmap-329.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0251",
    "title": "Castello Waterfront",
    "caption": "F. Ongania, 1890",
    "creator": "Unknown Artist",
    "year": 1890,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.43198, "lng": 12.3509 },
    "imageFile": "Venmap-33.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0252",
    "title": "Grand Canal view Near Train Station",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.439798, "lng": 12.320692 },
    "imageFile": "Venmap-330.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0253",
    "title": "Via Garibaldi",
    "caption": "Iddi Pietro, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.432027, "lng": 12.351108 },
    "imageFile": "Venmap-331.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0254",
    "title": "Children at well in Campo dei Mori",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445448, "lng": 12.332011 },
    "imageFile": "Venmap-332.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0255",
    "title": "Rio S. Girolamo",
    "caption": "F. Ongania, 1890",
    "creator": "Unknown Artist",
    "year": 2015,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.445829, "lng": 12.32347 },
    "imageFile": "Venmap-34.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0256",
    "title": "Zattere Waterfront",
    "caption": "Unknown, About 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429682, "lng": 12.325557 },
    "imageFile": "Venmap-35.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0257",
    "title": "Water Carriers",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434171, "lng": 12.339548 },
    "imageFile": "Venmap-36.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0258",
    "title": "Campo Santa Maria Zobenigo",
    "caption": "Canaletto, 1730s",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.432465, "lng": 12.333111 },
    "imageFile": "Venmap-37.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0259",
    "title": "Campiello Querini",
    "caption": "Auguste Léon, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436524, "lng": 12.340861 },
    "imageFile": "Venmap-39.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0260",
    "title": "Campo Santa Maria Formosa",
    "caption": "",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437408, "lng": 12.340876 },
    "imageFile": "Venmap-4.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0261",
    "title": "Rio Mendicanti",
    "caption": "Auguste Léon, early 20th century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439445, "lng": 12.341272 },
    "imageFile": "Venmap-40.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0262",
    "title": "Campo San Provolo",
    "caption": "Auguste Léon, early 20th century",
    "creator": "Unknown Artist",
    "year": 2016,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434974, "lng": 12.342479 },
    "imageFile": "Venmap-41.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0263",
    "title": "View of San Marco from the Lagoon",
    "caption": "Canaletto, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.432726, "lng": 12.340352 },
    "imageFile": "Venmap-42.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0264",
    "title": "The Rialto Bridge",
    "caption": "Michele Mareschi, 18th Century",
    "creator": "Unknown Artist",
    "year": 2017,
    "mediaType": "painting",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438066, "lng": 12.335499 },
    "imageFile": "Venmap-43.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0265",
    "title": "Rialto Bridge",
    "caption": "Francesco Guardi, 18th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437582, "lng": 12.335737 },
    "imageFile": "Venmap-44.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0266",
    "title": "Columns of the Doge's Palace",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433984, "lng": 12.339881 },
    "imageFile": "Venmap-45.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0267",
    "title": "Porta della Carta",
    "caption": "Domenico Bresolin, 1850s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434171, "lng": 12.339548 },
    "imageFile": "Venmap-46.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0268",
    "title": "Gates of the Arsenale",
    "caption": "Tomaso Filippi, 1862",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434727, "lng": 12.349845 },
    "imageFile": "Venmap-47.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0269",
    "title": "View of San Marco from San Giorgio Bell Tower",
    "caption": "Carlo Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.429544, "lng": 12.343802 },
    "imageFile": "Venmap-48.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0270",
    "title": "Corte Soresina",
    "caption": "Tommaso Filippi, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.431173, "lng": 12.355584 },
    "imageFile": "Venmap-49.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0271",
    "title": "Ponte San Giuseppi de Castello",
    "caption": "John Singer Sargent",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.430618, "lng": 12.356647 },
    "imageFile": "Venmap-5.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0272",
    "title": "Guglie Bridge and Rio Tera San Leonardo",
    "caption": "C. Naya, abt. 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.443697, "lng": 12.325659 },
    "imageFile": "Venmap-50.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0273",
    "title": "Fondamenta de la Fabbrica dei Tabacchi",
    "caption": "Ottoline Morrell, Late 19th century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437085, "lng": 12.319472 },
    "imageFile": "Venmap-51.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0274",
    "title": "Well in Campo San Giovanni e Paolo",
    "caption": "Giovanni Battista Brusa, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439081, "lng": 12.341666 },
    "imageFile": "Venmap-52.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0275",
    "title": "The New Bell Tower",
    "caption": "Unknown, about 1910",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433894, "lng": 12.337712 },
    "imageFile": "Venmap-53.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0276",
    "title": "View of the Horses of San Marco and the Clock Tower",
    "caption": "F. Ongania, 1898",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43436, "lng": 12.339426 },
    "imageFile": "Venmap-54.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0277",
    "title": "High Water in St. Mark's Square",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43388, "lng": 12.337717 },
    "imageFile": "Venmap-55.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0278",
    "title": "Calle Rampini",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.43862, "lng": 12.331299 },
    "imageFile": "Venmap-56.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0279",
    "title": "C. Naya, Late 19th Century",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434707, "lng": 12.343017 },
    "imageFile": "Venmap-57.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0280",
    "title": "Santa Maria dell Orto",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 1900,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.446006, "lng": 12.332316 },
    "imageFile": "Venmap-58.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0281",
    "title": "Strining beads, Campo San Pietro di Castello",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434244, "lng": 12.359147 },
    "imageFile": "Venmap-59.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0282",
    "title": "Punta della Dogana",
    "caption": "Julius LeBlanc Stewart",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "painting",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.430545, "lng": 12.336173 },
    "imageFile": "Venmap-6.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0283",
    "title": "San Giovanni Evangelista",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.438273, "lng": 12.326383 },
    "imageFile": "Venmap-60.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0284",
    "title": "Palazzo Dario",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431246, "lng": 12.332526 },
    "imageFile": "Venmap-61.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0285",
    "title": "Grand Canal view from the Academia Bridge",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431687, "lng": 12.328984 },
    "imageFile": "Venmap-62.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0286",
    "title": "Scuola grande di San Rocco",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.436742, "lng": 12.325587 },
    "imageFile": "Venmap-63.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0287",
    "title": "Entrance portal, Basilica Santi Giovanni e paolo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43943, "lng": 12.341491 },
    "imageFile": "Venmap-64.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0288",
    "title": "Piraeus Lion at the Arsenale",
    "caption": "Unknown, 1850s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434752, "lng": 12.350057 },
    "imageFile": "Venmap-65.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0289",
    "title": "Gate of the Bell Tower Loggia",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434165, "lng": 12.339316 },
    "imageFile": "Venmap-66.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0290",
    "title": "View from Campo della Salute",
    "caption": "Unknown, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43108, "lng": 12.33497 },
    "imageFile": "Venmap-67.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0291",
    "title": "Campo San Martino",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.434835, "lng": 12.348774 },
    "imageFile": "Venmap-68.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0292",
    "title": "Basilica and Campanile",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433894, "lng": 12.337712 },
    "imageFile": "Venmap-69.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0293",
    "title": "Santa Maria dei Miracoli",
    "caption": "Unknown",
    "creator": "Unknown Artist",
    "year": 2005,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439771, "lng": 12.339327 },
    "imageFile": "Venmap-7.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0294",
    "title": "Riva degli Schiavoni and Hotel Danieli",
    "caption": "C.Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433736, "lng": 12.342459 },
    "imageFile": "Venmap-70.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0295",
    "title": "Fish Market Near the Guglie Bridge",
    "caption": "Tommaso Filippi, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.443679, "lng": 12.325479 },
    "imageFile": "Venmap-71.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0296",
    "title": "St. Mark's Basilica",
    "caption": "Unknown, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434087, "lng": 12.338274 },
    "imageFile": "Venmap-72.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0297",
    "title": "Laundry Day in Campo San Polo",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437674, "lng": 12.329877 },
    "imageFile": "Venmap-73.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0298",
    "title": "Palazzo Contarini Fasan",
    "caption": "Carlo Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.431374, "lng": 12.330083 },
    "imageFile": "Venmap-74.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0299",
    "title": "Doge's Palace and Ponte della Paglia",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433263, "lng": 12.341606 },
    "imageFile": "Venmap-75.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0300",
    "title": "Horses of San Marco",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434562, "lng": 12.339308 },
    "imageFile": "Venmap-76.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0301",
    "title": "Facade of St. Mark's",
    "caption": "Carlo Ponti, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433934, "lng": 12.339212 },
    "imageFile": "Venmap-77.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0302",
    "title": "Bridge of Sighs",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433668, "lng": 12.341029 },
    "imageFile": "Venmap-78.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0303",
    "title": "Ramo Parangon",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438327, "lng": 12.335241 },
    "imageFile": "Venmap-79.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0304",
    "title": "Bridge of Sighs",
    "caption": "Photochrom Zürich, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433668, "lng": 12.341029 },
    "imageFile": "Venmap-8.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0305",
    "title": "Steps of the Rialto Bridge",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438319, "lng": 12.335563 },
    "imageFile": "Venmap-80.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0306",
    "title": "Bell Tower, Church of San Rocco",
    "caption": "Bell Tower, Church of San Rocco",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.437201, "lng": 12.324387 },
    "imageFile": "Venmap-81.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0307",
    "title": "Merceria",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.436208, "lng": 12.337577 },
    "imageFile": "Venmap-82.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0308",
    "title": "San Trovaso Squero",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Dorsoduro",
    "coordinates": { "lat": 45.429998, "lng": 12.325993 },
    "imageFile": "Venmap-83.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0309",
    "title": "Rio Tera San leonardo",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.44372, "lng": 12.326591 },
    "imageFile": "Venmap-84.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0310",
    "title": "View of Ruga dei Oresi from the Rialto Bridge",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.438232, "lng": 12.335675 },
    "imageFile": "Venmap-85.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0311",
    "title": "Calle Paradiso",
    "caption": "Paolo Salviati, late 19th century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43755, "lng": 12.339947 },
    "imageFile": "Venmap-86.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0312",
    "title": "Campo San Moise",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433134, "lng": 12.335754 },
    "imageFile": "Venmap-87.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0313",
    "title": "Corner of the Basilica near the Porta della Carta",
    "caption": "Unknown, Mid 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.434165, "lng": 12.339316 },
    "imageFile": "Venmap-88.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0314",
    "title": "Palazzo Giustinian",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Polo",
    "coordinates": { "lat": 45.434107, "lng": 12.327171 },
    "imageFile": "Venmap-89.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0315",
    "title": "Rialto Bridge",
    "caption": "Photochrom Zürich, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437688, "lng": 12.335088 },
    "imageFile": "Venmap-9.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0316",
    "title": "View of Rialto Bridge",
    "caption": "Domenico Bresolin, 1850s",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.43889, "lng": 12.336275 },
    "imageFile": "Venmap-90.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0317",
    "title": "Campo Manin",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.435181, "lng": 12.333926 },
    "imageFile": "Venmap-91.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0318",
    "title": "Arsenale Land Gate",
    "caption": "Unknown, Early 20th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.43473, "lng": 12.349824 },
    "imageFile": "Venmap-92.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0319",
    "title": "Rio Santa Fosca",
    "caption": "Fratelli Alinari, around 1900",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Cannaregio",
    "coordinates": { "lat": 45.443532, "lng": 12.331854 },
    "imageFile": "Venmap-93.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0320",
    "title": "The Piazzetta and Clock Tower",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": "Circa 19th Century",
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43396, "lng": 12.339385 },
    "imageFile": "Venmap-94.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0321",
    "title": "Scola Grande di San Marco and  Santi Giovanni e Paolo",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Historic Venice",
    "coordinates": { "lat": 45.439314, "lng": 12.340919 },
    "imageFile": "Venmap-95.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0322",
    "title": "Fishing Boats Near the Arsenale",
    "caption": "P. Salviati, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "Castello",
    "coordinates": { "lat": 45.435442, "lng": 12.359929 },
    "imageFile": "Venmap-96.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0323",
    "title": "View from the Doge's Palace",
    "caption": "C. Naya, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.433623, "lng": 12.340056 },
    "imageFile": "Venmap-97.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0324",
    "title": "Well in the Courtyard of the Doge's Palace",
    "caption": "Unknown, Late 19th Century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.43406, "lng": 12.34019 },
    "imageFile": "Venmap-98.webp",
    "rights": "Public Domain",
    "inBounds": True
  },
  {
    "id": "venice_0325",
    "title": "View toward the Rialto Bridge",
    "caption": "F. Ongania, Early 20th century",
    "creator": "Unknown Artist",
    "year": 2019,
    "mediaType": "photo",
    "sestiere": "San Marco",
    "coordinates": { "lat": 45.437638, "lng": 12.336692 },
    "imageFile": "Venmap-99.webp",
    "rights": "Public Domain",
    "inBounds": True
  }
]
